USE [master]
GO

CREATE DATABASE [CarsDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarsDatabase', FILENAME = N'C:\Users\andre.dublin\CarsDatabase.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CarsDatabase_log', FILENAME = N'C:\Users\andre.dublin\CarsDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CarsDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarsDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarsDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarsDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarsDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarsDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarsDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarsDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarsDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarsDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarsDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarsDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarsDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarsDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarsDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarsDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarsDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarsDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarsDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarsDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarsDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarsDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarsDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarsDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarsDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarsDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [CarsDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarsDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarsDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarsDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CarsDatabase] SET  READ_WRITE 
GO


